package ObjectModel;

import java.util.HashMap;
import java.util.Map;

/**
 * The DatasetFeature Object stores all the fields generated by the FeatureExtraction class.
 * @author BUI DUONG
 */
public class DatasetFeature {
    /**
     * total number of Observations
     */
    public int numOfObservations;
    
    /**
     * It stores the co-occurrences of Feature and Category values
     */
    public Map<String, Map<String, Integer>> featureCategoryJointCount;
    
    /**
     * Measures how many times each category was found in the training dataset.
     */
    public Map<String, Integer> categoryCounts;

    /**
     * Constructor
     */
    public DatasetFeature() {
        this.numOfObservations = 0;
        this.featureCategoryJointCount = new HashMap<>();
        this.categoryCounts = new HashMap<>();
    }
}
