//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Duong's Data/MyMoney/Mobile Software/DLLIB/HWDBF/src/DLDBM/DLClassInterface.java
//
//  Created by buiduong on 1/16/14.
//

#include "DLDBM/DLClassInterface.h"
#include "IOSObjectArray.h"


@interface DLDBMDLClassInterface : NSObject
@end

@implementation DLDBMDLClassInterface

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "PrimaryKey", NULL, "LIOSObjectArray", 0x401, NULL },
    { "ReferTo", NULL, "LIOSObjectArray", 0x401, NULL },
    { "ReferBy", NULL, "LIOSObjectArray", 0x401, NULL },
    { "IdentityColumn", NULL, "LNSString", 0x401, NULL },
    { "OrderColumn", NULL, "LIOSObjectArray", 0x401, NULL },
  };
  static J2ObjcClassInfo _DLDBMDLClassInterface = { "DLClassInterface", "DLDBM", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_DLDBMDLClassInterface;
}

@end
