//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Duong's Data/MyMoney/Mobile Software/DLLIB/HWDBF/src/DLDBM/DLClassTableInfo.java
//
//  Created by buiduong on 1/16/14.
//

#include "DLDBM/DLClassTableInfo.h"
#include "IOSObjectArray.h"

@implementation DLDBMDLClassTableInfo

- (NSString *)getClassName {
  return ClassName_;
}

- (void)setReferFromWithNSStringArray:(IOSObjectArray *)ReferFrom {
  DLDBMDLClassTableInfo_set_ReferFrom_(self, ReferFrom);
}

- (IOSObjectArray *)getReferFrom {
  return ReferFrom_;
}

- (IOSObjectArray *)getFields {
  return Fields_;
}

- (id)init {
  return [super init];
}

- (IOSObjectArray *)getTypes {
  return Types_;
}

- (void)setClassNameWithNSString:(NSString *)ClassName {
  DLDBMDLClassTableInfo_set_ClassName_(self, ClassName);
}

- (void)setFieldsWithNSStringArray:(IOSObjectArray *)Fields {
  DLDBMDLClassTableInfo_set_Fields_(self, Fields);
}

- (void)setTypesWithNSStringArray:(IOSObjectArray *)Types {
  DLDBMDLClassTableInfo_set_Types_(self, Types);
}

- (id)initWithNSString:(NSString *)ClassName
     withNSStringArray:(IOSObjectArray *)Fields
     withNSStringArray:(IOSObjectArray *)Types {
  if (self = [super init]) {
    DLDBMDLClassTableInfo_set_ClassName_(self, ClassName);
    DLDBMDLClassTableInfo_set_Fields_(self, Fields);
    DLDBMDLClassTableInfo_set_Types_(self, Types);
  }
  return self;
}

- (IOSObjectArray *)getPrimaryKey {
  return primaryKey_;
}

- (void)setPrimaryKeyWithNSStringArray:(IOSObjectArray *)primaryKey {
  DLDBMDLClassTableInfo_set_primaryKey_(self, primaryKey);
}

- (IOSObjectArray *)getReferTo {
  return ReferTo_;
}

- (void)setReferToWithNSStringArray:(IOSObjectArray *)ReferTo {
  DLDBMDLClassTableInfo_set_ReferTo_(self, ReferTo);
}

- (NSString *)getIdentityColumn {
  return IdentityColumn_;
}

- (void)setIdentityColumnWithNSString:(NSString *)IdentityColumn {
  DLDBMDLClassTableInfo_set_IdentityColumn_(self, IdentityColumn);
}

- (void)dealloc {
  DLDBMDLClassTableInfo_set_IdentityColumn_(self, nil);
  DLDBMDLClassTableInfo_set_ReferFrom_(self, nil);
  DLDBMDLClassTableInfo_set_ReferTo_(self, nil);
  DLDBMDLClassTableInfo_set_primaryKey_(self, nil);
  DLDBMDLClassTableInfo_set_Types_(self, nil);
  DLDBMDLClassTableInfo_set_Fields_(self, nil);
  DLDBMDLClassTableInfo_set_ClassName_(self, nil);
  [super dealloc];
}

- (void)copyAllFieldsTo:(DLDBMDLClassTableInfo *)other {
  [super copyAllFieldsTo:other];
  DLDBMDLClassTableInfo_set_ClassName_(other, ClassName_);
  DLDBMDLClassTableInfo_set_Fields_(other, Fields_);
  DLDBMDLClassTableInfo_set_IdentityColumn_(other, IdentityColumn_);
  DLDBMDLClassTableInfo_set_ReferFrom_(other, ReferFrom_);
  DLDBMDLClassTableInfo_set_ReferTo_(other, ReferTo_);
  DLDBMDLClassTableInfo_set_Types_(other, Types_);
  DLDBMDLClassTableInfo_set_primaryKey_(other, primaryKey_);
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getClassName", NULL, "LNSString", 0x1, NULL },
    { "getReferFrom", NULL, "LIOSObjectArray", 0x1, NULL },
    { "getFields", NULL, "LIOSObjectArray", 0x1, NULL },
    { "getTypes", NULL, "LIOSObjectArray", 0x1, NULL },
    { "getPrimaryKey", NULL, "LIOSObjectArray", 0x1, NULL },
    { "getReferTo", NULL, "LIOSObjectArray", 0x1, NULL },
    { "getIdentityColumn", NULL, "LNSString", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "ClassName_", NULL, 0x0, "LNSString" },
    { "Fields_", NULL, 0x0, "LIOSObjectArray" },
    { "Types_", NULL, 0x0, "LIOSObjectArray" },
  };
  static J2ObjcClassInfo _DLDBMDLClassTableInfo = { "DLClassTableInfo", "DLDBM", NULL, 0x1, 7, methods, 3, fields, 0, NULL};
  return &_DLDBMDLClassTableInfo;
}

@end
