//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Duong's Data/MyMoney/Mobile Software/DLLIB/HWDBF/src/DLDBM/DLClassTableInfo.java
//
//  Created by buiduong on 1/16/14.
//

#ifndef _DLDBMDLClassTableInfo_H_
#define _DLDBMDLClassTableInfo_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@interface DLDBMDLClassTableInfo : NSObject {
 @public
  NSString *ClassName_;
  IOSObjectArray *Fields_;
  IOSObjectArray *Types_;
  IOSObjectArray *primaryKey_;
  IOSObjectArray *ReferTo_;
  IOSObjectArray *ReferFrom_;
  NSString *IdentityColumn_;
}

- (NSString *)getClassName;
- (void)setReferFromWithNSStringArray:(IOSObjectArray *)ReferFrom;
- (IOSObjectArray *)getReferFrom;
- (IOSObjectArray *)getFields;
- (id)init;
- (IOSObjectArray *)getTypes;
- (void)setClassNameWithNSString:(NSString *)ClassName;
- (void)setFieldsWithNSStringArray:(IOSObjectArray *)Fields;
- (void)setTypesWithNSStringArray:(IOSObjectArray *)Types;
- (id)initWithNSString:(NSString *)ClassName
     withNSStringArray:(IOSObjectArray *)Fields
     withNSStringArray:(IOSObjectArray *)Types;
- (IOSObjectArray *)getPrimaryKey;
- (void)setPrimaryKeyWithNSStringArray:(IOSObjectArray *)primaryKey;
- (IOSObjectArray *)getReferTo;
- (void)setReferToWithNSStringArray:(IOSObjectArray *)ReferTo;
- (NSString *)getIdentityColumn;
- (void)setIdentityColumnWithNSString:(NSString *)IdentityColumn;
- (void)copyAllFieldsTo:(DLDBMDLClassTableInfo *)other;
@end

J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, ClassName_, NSString *)
J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, Fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, Types_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, primaryKey_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, ReferTo_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, ReferFrom_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(DLDBMDLClassTableInfo, IdentityColumn_, NSString *)

#endif // _DLDBMDLClassTableInfo_H_
