//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Duong's Data/MyMoney/Mobile Software/DLLIB/HWDBF/src/DLDBM/DLClassInterface.java
//
//  Created by buiduong on 1/16/14.
//

#ifndef _DLDBMDLClassInterface_H_
#define _DLDBMDLClassInterface_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@protocol DLDBMDLClassInterface < NSObject, JavaObject >
- (IOSObjectArray *)PrimaryKey;
- (IOSObjectArray *)ReferTo;
- (IOSObjectArray *)ReferBy;
- (NSString *)IdentityColumn;
- (IOSObjectArray *)OrderColumn;
@end

#endif // _DLDBMDLClassInterface_H_
