//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Duong's Data/MyMoney/Mobile Software/DLLIB/HWDBF/src/DLMath/DLMatrix.java
//
//  Created by buiduong on 1/16/14.
//

#ifndef _DLMathDLMatrix_H_
#define _DLMathDLMatrix_H_

@class IOSIntArray;
@class IOSObjectArray;

#import "JreEmulation.h"

@interface DLMathDLMatrix : NSObject {
}

+ (void)displayMatrixWithIntArray2:(IOSObjectArray *)maxtrix;
+ (IOSObjectArray *)multiplyMatrixWithIntArray2:(IOSObjectArray *)maxtrix1
                                  withIntArray2:(IOSObjectArray *)maxtrix2;
+ (IOSIntArray *)getRowVectorWithIntArray2:(IOSObjectArray *)matrix
                                   withInt:(int)row;
+ (IOSIntArray *)getColVectorWithIntArray2:(IOSObjectArray *)matrix
                                   withInt:(int)col;
+ (int)multiplyVectorWithIntArray:(IOSIntArray *)vector1
                     withIntArray:(IOSIntArray *)vector2;
- (id)init;
@end

#endif // _DLMathDLMatrix_H_
